In [8]:
import pandas as pd

data = pd.read_csv("datas/student_performance.csv")

display(data.head())
display(len(data))

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   
3              5               52                        Yes            5   
4              7               75                         No            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

10000

타겟 변수, 특성 분리

In [6]:
from sklearn.model_selection import train_test_split

X = data.drop(['Extracurricular Activities', 'Performance Index'], axis=1)
y = data['Performance Index']

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=20)

표준화

In [9]:
from sklearn.preprocessing import StandardScaler

scale_data = ['Hours Studied', 'Previous Scores', 'Sleep Hours', 'Sample Question Papers Practiced']

scaler = StandardScaler()
X_train[scale_data] = scaler.fit_transform(X_train[scale_data])
X_valid[scale_data] = scaler.transform(X_valid[scale_data])

선형 회귀 모델 구축

In [37]:
from sklearn.linear_model import LinearRegression

LR_model = LinearRegression()
LR_model.fit(X_train, y_train)
y_predict = LR_model.predict(X_valid)
y_predict

array([56.27785951, 27.86497177, 48.17854744, ..., 18.28957919,
       73.32772182, 91.1108026 ])

선형 회귀 성능 평가

In [38]:
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error

LR_rmse = np.sqrt(mean_squared_error(y_valid, y_predict))
LR_mae = mean_absolute_error(y_valid, y_predict)

print(f'LR_RMSE: {LR_rmse}')
print(f'LR_MAE: {LR_mae}')

LR_RMSE: 2.0650183714499204
LR_MAE: 1.645633661709989


랜덤 포레스트 모델 구축

In [33]:
from sklearn.ensemble import RandomForestRegressor

RF_model = RandomForestRegressor()
RF_model.fit(X_train, y_train)
y_predict = RF_model.predict(X_valid)
y_predict

array([56.31      , 29.67      , 48.84161905, ..., 18.04333333,
       72.29333333, 91.98316667])

In [34]:
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error

LR_rmse = np.sqrt(mean_squared_error(y_valid, y_predict))
LR_mae = mean_absolute_error(y_valid, y_predict)

print(f'LR_RMSE: {LR_rmse}')
print(f'LR_MAE: {LR_mae}')

LR_RMSE: 2.383888666113345
LR_MAE: 1.8869353086219336


In [39]:
# 모델을 사용하여 test 데이터셋에 대한 예측을 수행합니다.
X_test = data.drop(['Extracurricular Activities', 'Performance Index'], axis=1)
X_test[scale_data] = scaler.transform(X_test[scale_data])
test_prediction = RF_model.predict(X_test)
test_prediction

array([90.224     , 64.37333333, 44.61      , ..., 73.5       ,
       94.49      , 64.81054762])

데이터 프레임으로 결과 보기

In [40]:
res = pd.DataFrame({
    '실제 성적': data["Performance Index"],
    '예측한 성적': test_prediction
})
res.head()

실제 성적     예측한 성적
0   91.0  90.224000
1   65.0  64.373333
2   45.0  44.610000
3   36.0  35.886333
4   66.0  66.190000